
version: '3.7'

services:

  nginx:
    depends_on:
      - web
  web:
    depends_on:
      - creator
      - custom-start-points
      - exercises-start-points
      - languages-start-points
      - dashboard
      - differ
      - repler
      - runner
      - saver
      - shas

  dashboard:
    depends_on:
      - saver

  differ:
    depends_on:
      - saver
