
version: '3.7'

services:

  nginx:
    depends_on:
      - web
      - creator
      - custom-start-points
      - exercises-start-points
      - languages-start-points
      - dashboard
      - differ
      - saver

  web:
    depends_on:
      - runner
      - saver

  dashboard:
    depends_on:
      - saver

  differ:
    depends_on:
      - saver
