
version: '3.7'

services:
# env-vars come from cyberdojo/versioner:latest

  nginx:
    image: ${CYBER_DOJO_NGINX_IMAGE}:${CYBER_DOJO_NGINX_TAG}

  # - - - - - - - - - - - - - - - - - - - - - - - -
  # start-points
  # see [cyber-dojo up --help] for details on how to override these
  custom-start-points:
    image: ${CYBER_DOJO_CUSTOM_START_POINTS}
  exercises-start-points:
    image: ${CYBER_DOJO_EXERCISES_START_POINTS}
  languages-start-points:
    image: ${CYBER_DOJO_LANGUAGES_START_POINTS}

  # - - - - - - - - - - - - - - - - - - - - - - - -
  creator:
    image: ${CYBER_DOJO_CREATOR_IMAGE}:${CYBER_DOJO_CREATOR_TAG}

  model:
    image: ${CYBER_DOJO_MODEL_IMAGE}:${CYBER_DOJO_MODEL_TAG}

  # - - - - - - - - - - - - - - - - - - - - - - - -
  # main services
  web:
    image: ${CYBER_DOJO_WEB_IMAGE}:${CYBER_DOJO_WEB_TAG}
  differ:
    image: ${CYBER_DOJO_DIFFER_IMAGE}:${CYBER_DOJO_DIFFER_TAG}
  repler:
    image: ${CYBER_DOJO_REPLER_IMAGE}:${CYBER_DOJO_REPLER_TAG}
  runner:
    image: ${CYBER_DOJO_RUNNER_IMAGE}:${CYBER_DOJO_RUNNER_TAG}
  saver:
    image: ${CYBER_DOJO_SAVER_IMAGE}:${CYBER_DOJO_SAVER_TAG}
  shas:
    image: ${CYBER_DOJO_SHAS_IMAGE}:${CYBER_DOJO_SHAS_TAG}
