
version: '3.7'

networks:
  cyber-dojo:
    driver: bridge
    name: cyber-dojo

services:

  # - - - - - - - - - - - - - - - - - - - - - - -
  # multi-threaded front-end with http caching
  nginx:
    user: root
    init: true

  # - - - - - - - - - - - - - - - - - - - - - - -
  # main server (rails)
  web:
    user: nobody
    environment:
      - CYBER_DOJO_SHA
      - CYBER_DOJO_RELEASE

  # - - - - - - - - - - - - - - - - - - - - - - -
  # start-points
  custom-start-points:
    user: nobody
    read_only: true

  exercises-start-points:
    user: nobody
    read_only: true

  languages-start-points:
    user: nobody
    read_only: true

  # - - - - - - - - - - - - - - - - - - - - - - -
  creator:
    user: nobody
    read_only: true

  # - - - - - - - - - - - - - - - - - - - - - - -
  model:
    user: nobody
    read_only: true

  # - - - - - - - - - - - - - - - - - - - - - - -
  # 64 animals
  avatars:
    user: nobody
    read_only: true

  # - - - - - - - - - - - - - - - - - - - - - - -
  # provides access to repl via web-socket
  repler:
    user: root
    init: true
    read_only: true
    networks:
      - cyber-dojo
      - default

  # - - - - - - - - - - - - - - - - - - - - - - -
  # runs cyber-dojo.sh in time-boxed container, returns traffic-light colour
  runner:
    user: root
    read_only: true

  # - - - - - - - - - - - - - - - - - - - - - - -
  # diffs all the files in two test events
  differ:
    user: nobody
    read_only: true

  # - - - - - - - - - - - - - - - - - - - - - - -
  # stores groups/katas and code+tests for every test event
  saver:
    user: saver
    init: true
    read_only: true

  # - - - - - - - - - - - - - - - - - - - - - - -
  # shows shas of each service
  shas:
    user: nobody
    read_only: true
