
version: '3.7'

services:

  nginx:
    restart: on-failure

  web:
    restart: on-failure

  creator:
    restart: on-failure

  custom-start-points:
    restart: on-failure
  exercises-start-points:
    restart: on-failure
  languages-start-points:
    restart: on-failure

  avatars:
    restart: on-failure

  repler:
    restart: on-failure

  runner:
    restart: on-failure

  puller:
    restart: on-failure

  differ:
    restart: on-failure

  saver:
    restart: on-failure

  shas:
    restart: on-failure
