
version: '3.7'

services:

  creator:
    volumes:
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 10485760 # 10MB

  custom-start-points:
    volumes:
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 10485760 # 10MB

  exercises-start-points:
    volumes:
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 10485760 # 10MB

  languages-start-points:
    volumes:
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 10485760 # 10MB

  avatars:
    volumes:
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 10485760 # 10MB

  model:
    volumes:
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 10485760 # 10MB

  differ:
    volumes:
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 52428800 # 50MB

  repler:
    volumes:
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 52428800 # 50MB

  runner:
    volumes:
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 52428800 # 50MB

  saver:
    volumes:
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 10485760 # 10MB

  shas:
    volumes:
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 10485760 # 10MB
