
version: '3.7'

services:
  repler:
    volumes: [ "/var/run/docker.sock:/var/run/docker.sock" ]
  runner:
    volumes: [ "/var/run/docker.sock:/var/run/docker.sock" ]
  custom-start-points:
    volumes: [ "/var/run/docker.sock:/var/run/docker.sock" ]
  languages-start-points:
    volumes: [ "/var/run/docker.sock:/var/run/docker.sock" ]
  saver:
    volumes: [ "/cyber-dojo:/cyber-dojo:rw" ]
