
version: '3.7'

services:
  repler:
    volumes: [ "/var/run/docker.sock:/var/run/docker.sock" ]
  runner:
    volumes: [ "/var/run/docker.sock:/var/run/docker.sock" ]
  saver:
    volumes: [ "/Users/Shared/cyber-dojo:/cyber-dojo:rw" ]
