#!/bin/bash
set -e

# - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Uses straight delegation (to cyber-dojo-inner script) so
# this script can remain minimal and (hopefully) never need
# updating, even after you've run a [cyber-dojo update].
# - - - - - - - - - - - - - - - - - - - - - - - - - - - -

readonly VERSIONER_IMAGE=cyberdojo/versioner:latest
readonly ENV_VARS=$(docker run --rm ${VERSIONER_IMAGE} sh -c 'cat /app/.env')
readonly COMMANDER_VAR=$(echo "${ENV_VARS}" | grep CYBER_DOJO_COMMANDER_SHA)
readonly COMMANDER_SHA=$(echo ${COMMANDER_VAR:25:99})
readonly COMMANDER_TAG=${COMMANDER_SHA:0:7}
readonly COMMANDER_IMAGE=${COMMANDER_IMAGE:-cyberdojo/commander:${COMMANDER_TAG}}
readonly SCRIPT=cyber-dojo-inner

docker run \
  --entrypoint cat \
  --rm \
  ${COMMANDER_IMAGE} /app/${SCRIPT} \
    > /tmp/${SCRIPT}

chmod 700 /tmp/${SCRIPT}

/tmp/${SCRIPT} $@
