version: 2
jobs:
  build-test-tag-publish:

    machine:
      enabled: true

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Build image, test it, tag it, publish it
          command: |
            set -e
            # DOCKER_USER, DOCKER_PASS are in ci context
            echo "${DOCKER_PASS}" | docker login --username "${DOCKER_USER}" --password-stdin
            ./build_test_publish.sh
            docker logout

workflows:
  version: 2
  build:
    jobs:
      - build-test-tag-publish:
          context: cyberdojo-context
          filters:
            branches:
              only:
                  - master
